### ISSUE TITLE
Cannot click on empty lines

### ISSUE THREAD

**Issue by Itaborala** [cephasteom/zen-3#2]
The cursor is not clickable in empty lines, or it does not move to empty lines when they are clicked at.

Steps to reproduce:

- Write some code in zen, with empty lines separating different sections of the code. 
- Try to click on top of an empty line and verify that nothing happens, no cursor appears where it should be.

**Comment by cephasteom** [comment]
@Itaborala Looks like Monaco (the browser code editor) bug. Thanks for raising the issue.

**Comment by cephasteom** [comment]
@Itaborala thanks again for raising the issue. This has now been fixed and will be rolled out shortly.

CT.
